name: Generate and Release

on:
  workflow_dispatch:
  schedule:
    - cron: "0 16 * * 0"

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run generator
        run: |
          chmod +x generate.sh
          ./generate.sh private cn

      - name: Commit and push to release branch
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

          # 创建/切换 release 分支
          git checkout -B release

          # 添加生成文件
          git add *.rsc

          # 提交，如果没有变化就跳过
          git diff --cached --quiet || git commit -m "Auto update address lists $(date +%Y%m%d)"

          # 推送到远程 release 分支
          git push origin release --force
